jobs:
  build:
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          sleep 50
  build-win:
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          sleep 50
  build-mac:
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: |
          echo Hello, world!
          echo Hello, world!
          echo Hello, world!
          echo Hello, world!
          echo Hello, world!
          echo Hello, world!
          echo Hello, world!
          echo Hello, world!
          echo Hello, world!
          echo Hello, world!
          echo Hello, world!
          echo Hello, world!
          echo Hello, world!
          echo Hello, world!
          echo Hello, world!
          echo Hello, world!
          echo Hello, world!
          echo Hello, world!
          echo Hello, world!
          echo Hello, world!
          echo Hello, world!
          echo Hello, world!
          echo Hello, world!
          echo Hello, world!
          echo Hello, world!
          echo Hello, world!
          echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          echo test, and deploy your project.
          sleep 50
