name: Test Reuse 2

on:
  workflow_dispatch:
  schedule:
    - cron: '*/17 * * * *'

jobs:
  deploy-env:
    name: Create environment
    uses: github.com/shayki-organization/actions-lens4/blob/main/.github/workflows/use-2-.yml@v0.1
    with:
      test: test
