name: Test Reuse 2

on:
  workflow_dispatch:
  schedule:
    - cron: '*/17 * * * *'

jobs:
  deploy-env:
    name: Create environment
    uses: shayki-organization/actions-lens4/.github/workflows/test.yml@v0.1
    with:
      test: test
